In [1]:
import chromadb

In [2]:
import pandas as pd

In [3]:
data = pd.read_csv("chatdata.csv")

In [4]:
data

     Unnamed: 0            user_input          response_msg
0             0                    hi                 hello
1             1           how are you     fine, how are you
2             2                  fine     nice to know this
3             3           who are you         I'm a chatbot
4             4     where do you live  I live in a computer
..          ...                   ...                   ...
98           98          nice to know                  good
99           99            hw are you                 error
100         100             okkkkkkkk                 error
101         101                  gret                 error
102         102  kya name hai tumhara        My name is Bot

[103 rows x 3 columns]

In [5]:
data.columns

Index(['Unnamed: 0', 'user_input', 'response_msg'], dtype='str')

In [6]:
data.rename(columns={'Unnamed: 0': 'id'}, inplace=True)

In [7]:
data

      id            user_input          response_msg
0      0                    hi                 hello
1      1           how are you     fine, how are you
2      2                  fine     nice to know this
3      3           who are you         I'm a chatbot
4      4     where do you live  I live in a computer
..   ...                   ...                   ...
98    98          nice to know                  good
99    99            hw are you                 error
100  100             okkkkkkkk                 error
101  101                  gret                 error
102  102  kya name hai tumhara        My name is Bot

[103 rows x 3 columns]

In [10]:
data.to_csv("chatdata.csv", index=False)